PM_NAME=pmrutlddomains
SHORT_NAME=rutld
FULL_NAME=Rutld
DOMAINPRICE_URL=https://my.ru-tld.ru/manimg/userdata/json/domainprice_ru.json
COUNTRIES_URL=https://my.ru-tld.ru/manimg/userdata/json/country.json
RUTLD_PROD_URL=https://my.ru-tld.ru/manager/billmgr
#RUTLD_PROJECT_NAME=*.ru-tld.ru (Domains)
RUTLD_PROJECT_NAME=RU-TLD тестовый
CLASS_NAME=RuTld